# create an external HTTP load balancer.
apiVersion: v1
kind: Service
metadata:
  name: python-playground-frontend
spec:
  type: LoadBalancer
  selector:
    app: python-playground-frontend
  ports:
  - port: 80
    targetPort: 8080