apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: python-playground-fronted 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-playground-fronted
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50